name: Execute Script

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  execute_script:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Run script
        run: |
          chmod +x asset-store-script.sh  # Ensure script has executable permissions
          ./asset-store-script.sh abcd ${{ secrets.GITHUB_TOKEN }} 
