name: Execute Script

on:
  pull_request:
    types: [closed]

jobs:
  on_pr_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Test changed-files
        uses: actions/checkout@v4
    
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44    

      - name: Clone private repo 
        run: |
          git config --global user.email "mercyqueen71@gmail.com"
          git config --global user.name "MercyQueen"
          git clone https://MercyQueen:$PAT_TOKEN@github.com/MercyQueen/asset-store.git asset-store
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Run script
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          chmod +x asset-store-script.sh 
          ./asset-store-script.sh ${{ github.event.pull_request.base.ref }} ${{ secrets.GITHUB_TOKEN }}
